import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import Header from '../components/Header';
import styles from '../styles/Home.module.css';

export default function Home({ exploreData }) {
	return (
		<div>
			<Head>
				<title>Airbnb Clone</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<Banner />

			<main className="max-w-7xl mx-auto px-8 sm:px-16 ">
				<h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>

				{/* Pull some data from server API endpoints */}
				{exploreData?.map((item) => (
					// eslint-disable-next-line react/jsx-key
					<h1>{item.location}</h1>
				))}
			</main>
		</div>
	);
}
export async function getStaticProps() {
	const exploreData = await fetch('https://links.papareact.com/pyp').then(
		(res) => res.json()
	);

	return {
		props: {
			exploreData,
		},
	};
}
